import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "System Configuration | Sifaris",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    // <div className="min-h-[calc(100vh-2rem)] bg-[#dde4ee] max-w-[80%] border border-red-400 ml-auto  my-8 p-8">
    //   <div className="bg-white p-6 rounded-xl  ">{children}</div>
    // </div>
    <div className="bg-white p-12 rounded-xl">{children}</div>
  );
}
