"use client";
import * as crypto from "crypto";

import React, { useState } from "react";
import {
  Controller,
  useFieldArray,
  useForm,
  useFormContext,
} from "react-hook-form";

// INTERNAL API OR RESOURCE IMPORT
import ListBox from "@/components/ListBox";
import { Modal } from "@/components/Modal";
import Button from "@/components/Button";
import { InputField } from "@/components/InputField";
import { InputLabel } from "@/components/InputLabel";
import { InputTableFieldType, TableCreatorFieldType, TableSchema } from "../types";

// interfaces type
export interface TableGeneratorModalFormProps {
  isOpen: boolean;
  onOpen: () => void;
  onClose: () => void;
}



// COMPONENT
const TableGeneratorModalForm = ({
  isOpen,
  onClose,
}: TableGeneratorModalFormProps) => {
  // random id generator
  // keeping this inside the component create a new definition every time the component rerender which is exactly what we want
  function generateRandomUuid(): string {
    // built-in Node.js crypto module to generate a random UUID
    return Date.now() + crypto.randomBytes(16).toString("hex");
  }
  // form create form context accessor
  const formCreator = useFormContext<TableCreatorFieldType>();
  // dynmic input field
  const { append, prepend, remove, swap, move, insert } =
    useFieldArray<TableCreatorFieldType>({
      control: formCreator.control, // control props comes from useForm (optional: if you are using FormContext)
      name: "tableFields", // unique name for your Field Array
    });

  // react-hook form configuaration for the input modal
  const { register, setValue, reset, control, handleSubmit } =
    useForm<InputTableFieldType>({
      defaultValues: {
        type: "text",
        name: "",
        header: "",
        id: generateRandomUuid(),
        required: true,
        placeholder: "",
      },
    });

  // data to show in type dropdown list
  const TableInputTypeList: TableSchema["type"][] = [
    "text",
    "date",
    "email",
    "number",
  ];

  //   const InputTypeRegister = register("type");
  // console.log(InputTypeRegister)

  return (
    <>
      <Modal isOpen={isOpen} onClose={onClose}>
        <form
          onSubmit={handleSubmit((data) => {
            append({
              id: data.id,
              header: data.header,
              name: data.name,
              required: data.required,
              placeholder: data.placeholder,
              type: data.type,
            });

            reset();
            onClose();
          })}
          className="flex flex-col gap-5 py-6"
        >
          <div className="form-container flex flex-col gap-3">
            {/* TYPE OF THE INPUT FIELD */}
            <div>
              <InputLabel htmlFor="" labelName={"Table Input Type"} />
              <Controller
                control={control}
                render={({ field: { value, onChange } }) => {
                  return (
                    <>
                      <ListBox<TableSchema["type"]>
                        options={TableInputTypeList}
                        className="h-11 shadow-none"
                        valueExtractor={(item) => item}
                        labelExtractor={(item) => item}
                        value={value}
                        labelExtractorByValue={(value, options) =>
                          options.find((option) => option === value) ||
                          "select a type"
                        }
                        onChange={onChange}
                      />
                    </>
                  );
                }}
                name={"type"}
              />
            </div>
            {/* NAME OF THE table FIELD */}
            <div>
              <InputLabel labelName={"Table Input Name"} />
              <InputField {...register("name", { required: true })} />
              <p className="text-xs">
                Note: This will map as a input field in the form submission
              </p>
            </div>

            {/* LABEL OF THE INPUT FIELD  */}
            <div>
              <InputLabel labelName={"table header"} />
              <InputField {...register("header", { required: true })} />
            </div>
            {/* ID OF THE INPUT FIELD  */}
            {/* WHICH IS AUTOGENERATED */}
            {/* VALIDATION: IS INPUT FIELD REQURIED */}
            <div className="flex flex-col">
              <InputLabel labelName={"required"} />
              <input
                className="w-4 h-4 "
                type="checkbox"
                {...register("required")}
              />
            </div>
            {/* PLACEHOLDER OF THE INPUT  */}
            <div>
              <InputLabel labelName={"placeholder"} />
              <InputField {...register("placeholder")} />
            </div>
          </div>
          {/* BUTTON CONTAINER  */}
          <div className="flex items-center gap-32 justify-center ">
            {/* CANCEL BUTTON  */}
            <Button
              type="button"
              onClick={() => {
                onClose();
                reset();
              }}
              className=" rounded-md text-[#002147] text-[14px] font-medium border border-[#002147]"
            >
              Cancel
            </Button>

            {/* SUBMIT BUTTON  */}
            <Button className="rounded-md bg-[#002147] text-[14px] font-medium border border-[#002147] text-white ">
              Save Field
            </Button>
          </div>
        </form>
      </Modal>
    </>
  );
};

export default TableGeneratorModalForm;
